spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
   profiles: dev
   application:
    name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc: mysql://localhost:3306/flux              # 数据库名称
    username: root
    password: root
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.flux.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    

eureka:
  client:
    service-url:
      defaultZone: http://demo3003.com:7001/eureka/
  instance:
    instance-id: dept-8001
    prefer-ip-address: true
info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version: $project.version$
  负责人: 张三
  联系电话: 110
